#!/usr/bin/env sh

npm install

# Generate config file

echo "Mail server URL:"
read server

echo "Mail from address:"
read address

echo "Mail password:"
read password

printf "// App config - required by index.js\n" > config.js
printf "// Generated by /tools/install.sh\n\n" >> config.js

printf "var config = {\n" >> config.js
printf  "\troot: \"" >> config.js
pwd | tr -d "\n" >> config.js

printf "\",\n\tmailServer: \"" >> config.js
echo $server"\"," >> config.js

printf "\tmailFrom: \"" >> config.js
echo $address"\"," >> config.js

printf "\tmailPassord: \"" >> config.js
echo $password"\"" >> config.js
printf "}\n\n" >> config.js

printf "module.exports = config;\n\n" >> config.js

echo "config.js generated"

